---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: python
    tag: 2.7.13-wheezy

inputs:
- name: base-stemcell
- name: pcf-pipelines

outputs:
- name: brkt-stemcell

run:
  path: pcf-pipelines/brkt/tasks/create-brkt-stemcell/task.sh

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  URL:
  EMAIL:
  PASSWORD:
  METAVISOR_VERSION:
